#cloud-config
hostname: ${hostname}
manage_etc_hosts: true

package_update: true
package_upgrade: false

packages:
  - curl
  - ca-certificates
  - gnupg
  - python3
  - python3-pip

# Désactiver le mot de passe root, forcer l'accès par clé SSH uniquement
users:
  - name: root
    lock_passwd: true

runcmd:
  - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart ssh
